# Generated by Django 4.0.1 on 2022-02-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='product_name',
        ),
    ]
