# Generated by Django 4.0.3 on 2022-03-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_rename_product_cart_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
