# Generated by Django 4.0.3 on 2022-03-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count',
            new_name='quantity',
        ),
    ]
