# Generated by Django 4.0.1 on 2022-03-27 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0013_alter_cart_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
